#include "graph_metadata.h"

GraphMetadata ALL_GRAPHS[31] = {
    {
        .V = 6070,
        .E = 4645004,
        .Delta = 5460,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "A_1515153016_18",
    },
    {
        .V = 2810,
        .E = 1005214,
        .Delta = 2524,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "A7H4H_18",
    },
    {
        .V = 1603510,
        .E = 6304806,
        .Delta = 3550,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "bxb777_999_12",
    },
    {
        .V = 2210104,
        .E = 8807410,
        .Delta = 4196,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "BxB1100_999_54_2017",
    },
    {
        .V = 1010,
        .E = 60980,
        .Delta = 282,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "CBQsc100_200_11_1517",
    },
    {
        .V = 221651,
        .E = 12528006,
        .Delta = 12340,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "Gf12345_12111222_457_15",
    },
    {
        .V = 2135792,
        .E = 2162836,
        .Delta = 80,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "GRD99704280",
    },
    {
        .V = 970800,
        .E = 980400,
        .Delta = 100,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "GRD505041100",
    },
    {
        .V = 5576,
        .E = 6748,
        .Delta = 7,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "GRD22154753987",
    },
    {
        .V = 3277,
        .E = 1925226,
        .Delta = 1499,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "lux4",
    },
    {
        .V = 1789,
        .E = 875431,
        .Delta = 1788,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "R1789_875431_10",
    },
    {
        .V = 1999999,
        .E = 10123123,
        .Delta = 1999998,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "R1999999_10123123_1",
    },
    {
        .V = 385,
        .E = 19095,
        .Delta = 282,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "school1.col",
    },
    {
        .V = 100,
        .E = 1470,
        .Delta = 35,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "q10.corr",
    },
    {
        .V = 169,
        .E = 3328,
        .Delta = 48,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "q13.corr",
    },
    {
        .V = 410,
        .E = 23614,
        .Delta = 364,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "A1H75_18.txt",
    },
    {
        .V = 750,
        .E = 2670,
        .Delta = 72,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "bxb15_22_10.txt",
    },
    {
        .V = 1599,
        .E = 1598,
        .Delta = 2,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "C1599_1777.txt",
    },
    {
        .V = 3779,
        .E = 371357,
        .Delta = 240,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "CBQsv10_22_61.txt",
    },
    {
        .V = 23658,
        .E = 5586907,
        .Delta = 595,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "CBQsv1000_77_150.txt",
    },
    {
        .V = 148,
        .E = 147,
        .Delta = 2,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "Cne140_4.txt",
    },
    {
        .V = 20002,
        .E = 49601,
        .Delta = 5,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "DG100.txt",
    },
    {
        .V = 100,
        .E = 4950,
        .Delta = 99,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "KC.txt",
    },
    {
        .V = 500,
        .E = 124750,
        .Delta = 499,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "KD.txt",
    },
    {
        .V = 1000,
        .E = 499500,
        .Delta = 999,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "KM.txt",
    },
    {
        .V = 288,
        .E = 15019,
        .Delta = 130,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "lux1.txt",
    },
    {
        .V = 34,
        .E = 316,
        .Delta = 24,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "lux2.txt",
    },
    {
        .V = 43,
        .E = 373,
        .Delta = UNKNOWN,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "lux3.txt",
    },
    {
        .V = 3080,
        .E = 4303060,
        .Delta = 2977,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "Octo.txt",
    },
    {
        .V = 20482,
        .E = 56705,
        .Delta = 6,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "PG64.txt",
    },
    {
        .V = 22,
        .E = 93,
        .Delta = 21,
        .is_bipartite = UNKNOWN,
        .chromatic_number = UNKNOWN,
        .expected_order_natural = UNKNOWN,
        .expected_order_walshpowell = UNKNOWN,
        .filename = "R22_99_15.txt",
    },
};
